const stories = [
    {
        id:1,
        user_img:"/images/profile_pictures/1.webp"
    },
    {
        id:2,
        user_img:"/images/profile_pictures/2.jpeg"
    },
    {
        id:3,
        user_img:"/images/profile_pictures/3.jpeg"
    },
    {
        id:4,
        user_img:"/images/profile_pictures/4.jpg"
    },
    {
        id:5,
        user_img:"/images/profile_pictures/5.jpeg"
    },
    {
        id:6,
        user_img:"/images/profile_pictures/1.webp"
    },
    {
        id:7,
        user_img:"/images/profile_pictures/2.jpeg"
    },
    {
        id:8,
        user_img:"/images/profile_pictures/3.jpeg"
    },
    {
        id:9,
        user_img:"/images/profile_pictures/4.jpg"
    },
]

export default stories;